// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import envConfig from "./src/config/load-env";
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: envConfig.DATABASE_SESSION_POOLER,
    shadowDatabaseUrl: envConfig.DATABASE_TRANSACTION_POOLER,
  },
});
